swagger: '2.0'
info:
  title: net6apigateway
  description: SomeDesc
  version: '1.0'
schemes:
  - https
security:
  - api_key: [ ]
securityDefinitions:
  # This section configures basic authentication with an API key.
  api_key:
    type: "apiKey"
    name: "key"
    in: "query"
produces:
  - application/json
x-google-backend:
  address: https://net6service-oexclglnxq-uc.a.run.app/
paths:
  /some:
    get:
      tags:
        - Net6Test
      produces:
        - application/json
      parameters:
        - in: query
          name: arg
          required: true
          type: string
      operationId: getSome
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/Result'
definitions:
  Result:
    type: object
    properties:
      message:
        type: string
      date:
        format: date-time
        type: string